---
  root: true
  env:
    es6: true
    browser: true
    jquery: true
  extends: "eslint:recommended"
  rules:
    indent:
      - error
      - 2
    linebreak-style:
      - error
      - unix
    quotes:
      - error
      - single
      - avoidEscape: true
    semi:
      - error
      - always
